import type { Metadata } from "next";
import localFont from "next/font/local";
import ".././globals.css";
import LocaleSwitcher from "@/components/LocalSwitcher";

const neue = localFont({
  src: [
    {
      path: ".././fonts/NeueFrutigerWorld-Regular.woff",
      weight: "400",
    },

    {
      path: ".././fonts/NeueFrutigerWorld-Medium.woff",
      weight: "500",
    },

    {
      path: ".././fonts/NeueFrutigerWorld-Bold.woff",
      weight: "700",
    },

    {
      path: ".././fonts/NeueFrutigerWorld-Black.woff",
      weight: "800",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const lang = params?.lang || "ar"; // Default to 'ar' if no lang is provided

  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <body className={`${neue.className} antialiased`}>
        <LocaleSwitcher />
        <p>Current Language: {lang}</p>
        {children}
      </body>
    </html>
  );
}
